load("//javascript/typescript:build_defs.bzl", "ts_library")

ts_library(
    name = "add-to-dropdown-list",
    srcs = [
        "add-to-dropdown-list.component.spec.ts",
        "add-to-dropdown-list.component.ts",
    ],
)
