load("//javascript/typescript:build_defs.bzl", "ts_library")

ts_library(
    name = "edit-element-in-dropdown-list",
    srcs = [
        "edit-element-in-dropdown-list.component.spec.ts",
        "edit-element-in-dropdown-list.component.ts",
    ],
)
