load("//javascript/typescript:build_defs.bzl", "ts_library")

ts_library(
    name = "summary-spending",
    srcs = [
        "summary-spending.component.spec.ts",
        "summary-spending.component.ts",
    ],
)
