load("//javascript/typescript:build_defs.bzl", "ts_library")

ts_library(
    name = "add-transaction",
    srcs = [
        "add-transaction.component.spec.ts",
        "add-transaction.component.ts",
    ],
)
