load("//javascript/typescript:build_defs.bzl", "ts_library")

ts_library(
    name = "edit-transaction",
    srcs = [
        "edit-transaction.component.spec.ts",
        "edit-transaction.component.ts",
    ],
)
