load("//javascript/angular2:build_defs.bzl", "ng_module")

ng_module(
    name = "angular-material",
    srcs = [
        "angular-material.module.ts",
        "ng2-charts.ts",
    ],
    deps = [
        "//third_party/javascript/angular2:core",
        "//third_party/javascript/angular2:material_button",
        "//third_party/javascript/angular2:material_core",
        "//third_party/javascript/angular2:material_datepicker",
        "//third_party/javascript/angular2:material_dialog",
        "//third_party/javascript/angular2:material_form_field",
        "//third_party/javascript/angular2:material_icon",
        "//third_party/javascript/angular2:material_input",
        "//third_party/javascript/angular2:material_select",
        "//third_party/javascript/angular2:material_tabs",
    ],
)
