load("//javascript/typescript:build_defs.bzl", "ts_library")

ts_library(
    name = "app",
    srcs = [
        "app.component.spec.ts",
        "app.component.ts",
        "app.module.ts",
        "app-routing.module.ts",
    ],
)
