load("//javascript/typescript:build_defs.bzl", "ts_library")

ts_library(
    name = "transactions-list",
    srcs = [
        "transactions-list.component.spec.ts",
        "transactions-list.component.ts",
    ],
)
