load("//javascript/typescript:build_defs.bzl", "ts_library")

ts_library(
    name = "dropdown-lists",
    srcs = [
        "dropdown-lists.component.spec.ts",
        "dropdown-lists.component.ts",
    ],
)
